"""Render the AIShield catalog cover (1200x630) for the NetMind Product Arena listing.

Design constraints that matter here:

* The rule counts are NOT hardcoded. They are pulled from the live
  GET /api/v1/health `rules_breakdown`, so the cover can never advertise a stale
  number (the repo bans citing outdated rule counts). If the endpoint cannot be
  reached the script FAILS instead of guessing -- a cover with a wrong count is
  worse than no cover.
* Text is drawn with a real font, not generated by an image model, so the
  product name and the counts are pixel-exact. Image models garble small text.

Usage:
    python scripts/arena/make_cover.py                  # -> docs/assets/aishield-cover.png
    python scripts/arena/make_cover.py --out some.png
"""
import json
import os
import sys
import urllib.request

from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
BG_TOP = (11, 18, 32)
BG_BOTTOM = (15, 23, 42)
INK = (241, 245, 249)
MUTED = (148, 163, 184)
ACCENT = (238, 69, 96)        # the crimson already used across the site CSS
ACCENT_DIM = (122, 34, 52)
SKY = (56, 189, 248)

# Two independent endpoints. arena/health exposes both counts; health exposes the
# MCP total. Cross-checking them means a cover can never ship a number that the
# rest of the system disagrees with.
ARENA_HEALTH_URL = "https://aishield.tools/api/v1/arena/health"
HEALTH_URL = "https://aishield.tools/api/v1/health"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_OUT = os.path.join(ROOT, "docs", "assets", "aishield-cover.png")

FONT_BOLD = r"C:\Windows\Fonts\segoeuib.ttf"
FONT_REG = r"C:\Windows\Fonts\segoeui.ttf"


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "aishield-cover/1.0",
                                               "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=45) as r:
        return json.load(r)


def live_counts():
    """Return (mcp_rules, skill_rules) from the live API, cross-checked."""
    d = _get(ARENA_HEALTH_URL)
    mcp = d.get("mcp_rules")
    skill = d.get("skill_rules")
    if not isinstance(mcp, int) or not isinstance(skill, int):
        raise SystemExit("FAIL: no mcp_rules/skill_rules in %s\n%s"
                         % (ARENA_HEALTH_URL, json.dumps(d)[:300]))

    # cross-check the MCP count against the main health endpoint
    h = _get(HEALTH_URL)
    total = h.get("rules_count")
    rb = h.get("rules_breakdown") or {}
    if total != mcp and rb.get("total") != mcp:
        raise SystemExit("FAIL: rule count disagreement -- arena/health says mcp=%s, "
                         "health says rules_count=%s rules_breakdown=%s"
                         % (mcp, total, json.dumps(rb)[:200]))
    return mcp, skill


def font(path, size):
    return ImageFont.truetype(path, size)


def gradient(size):
    img = Image.new("RGB", size, BG_TOP)
    d = ImageDraw.Draw(img)
    for y in range(size[1]):
        t = y / float(size[1] - 1)
        d.line([(0, y), (size[0], y)], fill=(
            int(BG_TOP[0] + (BG_BOTTOM[0] - BG_TOP[0]) * t),
            int(BG_TOP[1] + (BG_BOTTOM[1] - BG_TOP[1]) * t),
            int(BG_TOP[2] + (BG_BOTTOM[2] - BG_TOP[2]) * t),
        ))
    return img


def glow(img, cx, cy, radius, color, strength=42):
    """Cheap radial glow: draw shrinking translucent ellipses onto an overlay."""
    ov = Image.new("RGBA", img.size, (0, 0, 0, 0))
    od = ImageDraw.Draw(ov)
    steps = 26
    for i in range(steps, 0, -1):
        t = i / float(steps)
        rr = radius * t
        a = int(strength * (1.0 - t) ** 2)
        od.ellipse([cx - rr, cy - rr, cx + rr, cy + rr], fill=color + (a,))
    img.paste(Image.alpha_composite(img.convert("RGBA"), ov).convert("RGB"), (0, 0))


def dot_grid(img, step=34, radius=1, color=(30, 41, 59), alpha=110):
    """Faint dot grid -- adds texture so the panel does not read as a flat slab."""
    ov = Image.new("RGBA", img.size, (0, 0, 0, 0))
    od = ImageDraw.Draw(ov)
    for y in range(step, img.size[1] - step, step):
        for x in range(step, img.size[0] - step, step):
            od.ellipse([x - radius, y - radius, x + radius, y + radius],
                       fill=color + (alpha,))
    return Image.alpha_composite(img.convert("RGBA"), ov).convert("RGB")


def shield(draw, cx, cy, w, h, fill, outline, width=5, check=True):
    hw, hh = w / 2.0, h / 2.0
    top = cy - hh
    pts = [
        (cx - hw, top),
        (cx + hw, top),
        (cx + hw, top + hh * 0.62),
        (cx + hw * 0.86, top + hh * 1.18),
        (cx + hw * 0.52, top + hh * 1.62),
        (cx, top + hh * 1.86),
        (cx - hw * 0.52, top + hh * 1.62),
        (cx - hw * 0.86, top + hh * 1.18),
        (cx - hw, top + hh * 0.62),
    ]
    draw.polygon(pts, fill=fill, outline=outline, width=width)
    if check:
        cw = w * 0.42
        p1 = (cx - cw * 0.62, cy + hh * 0.06)
        p2 = (cx - cw * 0.12, cy + hh * 0.52)
        p3 = (cx + cw * 0.78, cy - hh * 0.42)
        draw.line([p1, p2, p3], fill=(255, 255, 255), width=int(w * 0.11), joint="curve")


def pill(draw, x, y, text, f, fg, bg, pad_x=18, pad_y=11, border=None):
    tw = draw.textlength(text, font=f)
    asc, desc = f.getmetrics()
    th = asc + desc
    box = [x, y, x + tw + pad_x * 2, y + th + pad_y * 2]
    draw.rounded_rectangle(box, radius=(box[3] - box[1]) / 2.0, fill=bg,
                           outline=border, width=2 if border else 0)
    draw.text((x + pad_x, y + pad_y), text, font=f, fill=fg)
    return box[2] + 14


def main():
    out = DEFAULT_OUT
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]
    mcp, skill = live_counts()
    print("live counts: mcp=%d skill=%d" % (mcp, skill))

    img = gradient((W, H))
    img = dot_grid(img)
    glow(img, 170, 250, 320, ACCENT, strength=30)
    glow(img, 1080, 60, 280, SKY, strength=16)
    d = ImageDraw.Draw(img)

    # shield emblem
    shield(d, 172, 250, 176, 196, fill=(26, 20, 30), outline=ACCENT, width=6)

    # wordmark + tagline
    f_title = font(FONT_BOLD, 86)
    f_sub = font(FONT_REG, 29)
    f_pill = font(FONT_BOLD, 22)
    f_url = font(FONT_BOLD, 27)

    d.text((326, 134), "AIShield", font=f_title, fill=INK)
    d.text((330, 250), "Agent-native security scanner for", font=f_sub, fill=MUTED)
    d.text((330, 288), "MCP servers, Agent Skills, GPTs & prompts", font=f_sub, fill=MUTED)

    x = 330
    y = 356
    x = pill(d, x, y, "%d MCP rules" % mcp, f_pill, INK, (30, 41, 59))
    x = pill(d, x, y, "%d skill rules" % skill, f_pill, INK, (30, 41, 59))
    x = pill(d, x, y, "never executes", f_pill, ACCENT, (44, 20, 28), border=ACCENT)

    d.text((330, 438), "OWASP MCP Top 10  ·  ASI01-10  ·  zero dependencies", font=f_sub, fill=MUTED)
    d.text((330, 490), "aishield.tools", font=f_url, fill=ACCENT)

    # bottom accent rule + footer
    d.rectangle([0, H - 6, W, H], fill=ACCENT)
    f_foot = font(FONT_REG, 20)
    d.text((W - 80 - d.textlength("npm: aishield-mcp-server", font=f_foot), 498),
           "npm: aishield-mcp-server", font=f_foot, fill=(71, 85, 105))

    os.makedirs(os.path.dirname(out), exist_ok=True)
    img.save(out, "PNG", optimize=True)
    print("wrote %s (%d bytes, %dx%d)" % (out, os.path.getsize(out), W, H))


if __name__ == "__main__":
    main()
